
name: Deploy Auth-Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: CheckOut
      uses: actions/checkout@v3

    - name: Prepare script permissions
      run: |
        chmod 777 run.sh
    - name: stop docker
      run: |
        docker compose down
    
    #- name: Build container
    #  run: |
    #    if [[ -z $(docker ps -a -q -f name=backpy) ]]; then
    #      docker build -t backpy -f Dockerfile .
     #   else
     #     docker stop backpy && docker rm backpy && docker rmi backpy
     #     docker build -t backpy -f Dockerfile .
     #   fi
    - name: Run
      run: ./run.sh
